//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class searchDBEntities : DbContext
    {
        public searchDBEntities()
            : base("name=searchDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserInfo> UserInfoes { get; set; }
    
        public virtual ObjectResult<UserInfo> AllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserInfo>("AllUsers");
        }
    
        public virtual ObjectResult<UserInfo> AllUsers(MergeOption mergeOption)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserInfo>("AllUsers", mergeOption);
        }

        public System.Data.Entity.DbSet<SearchAPI.Models.AllUsers_Result> AllUsers_Result { get; set; }
    }
}
